### ISSUE TITLE
Commits on your behalf...and final home?

### ISSUE THREAD

**Issue by timholy** [JuliaGizmos/GtkReactive.jl#1]
Hi @jverzani and @shashi,

I've started working on this package. It began as GtkInteract, but I ended up feeling that it wasn't ideally suited for more sophisticated GUIs (largely because, after creating the minimal signals, it throws away the GtkWidget). I also didn't want to lock myself to a particular plotting toolkit, so I was going to have to ditch `@manipulate`. Since AFAICT that's the main point of GtkInteract, I decided that rather than try to force my vision on @jverzani this should just be a new package forked from GtkInteract (to give credit where credit is due).

I then copied Interact's `src/widgets.jl` here and gave @shashi credit. Then I started making changes; the current state is visible on the `dev` branch.

Before I go further, are these commits in your names acceptable to the two of you? If so, I'd eventually like to register this package, and likely host it with an organization. @shashi, would you prefer JuliaGizmos or JuliaGraphics? Either seems appropriate to me.

**Comment by jverzani** [comment]
This is great @timholy. I haven't looked at this codebase in so long and it would be nice for it to find a good use. I never resolved this issue (https://github.com/JuliaGraphics/Gtk.jl/issues/208), but perhaps it resolved on its own.

**Comment by timholy** [comment]
Ooh, interesting. No, I get a queasy feeling because I think I've seen it too but didn't stop to look carefully. I'll have a look. Thanks for calling my attention to it, and of course for the permission/enthusiasm.

**Comment by timholy** [comment]
Oh, wait, no. I was confusing it with "`map`  causes the function to be run once" issue (which surprised me).

**Comment by shashi** [comment]
This looks great! :)

I'm fine with having this in JuliaGizmos. I'll let you decide between that and JuliaGraphics.

**Comment by shashi** [comment]
So most of the code here is commented. Is the plan to uncomment them piece by piece?

After this is released, would GtkInteract be deprecated? I don't see a reason why you shouldn't re-implement `@manipulate` here... If some expression returns something that can be rendered to PNG or some MIME type Gtk can show, you can show a signal of it. Which is what `@manipulate` returns.

**Comment by shashi** [comment]
```
 Timers like fps are particularly important to "register" with refs: otherwise, you may keep using CPU resources even after you close the window, until the next garbage-collection event.
```
This means we should probably rip out the GC-related code in Reactive. It's been a cause of lots of confusion, plus you have to use something like this explicitly to clean up deterministically anyway.

**Comment by timholy** [comment]
> So most of the code here is commented. Is the plan to uncomment them piece by piece?

Yeah, this morning I've done `checkbox`, `togglebutton`, and `textarea`. Still quite a few to go, but getting there. I certainly wouldn't register it until it's a bit more complete. I will also provide some canvas utilities.

> After this is released, would GtkInteract be deprecated?

It's never been released as a package. I don't see any reason it can't continue to exist, however. Maybe there is a way to implement `@manipulate`, I just haven't thought about it.

> This means we should probably rip out the GC-related code in Reactive. 

I should first clarify that the README is mostly a placeholder and that line is not one that I've edited carefully; the specific mechanism it describes is not going to be present in the final version. Nevertheless, I don't disagree. You can see that I've taken the strategy of defining my widgets like this:
```julia
immutable Slider{T<:Number} <: InputWidget{T}
    signal::AbstractSignal{T}
    widget::GtkScaleLeaf
    id::Culong
    preserved::Vector
end
```
`id` is for manipulating the callback mechanism provided by Gtk, and `preserved` is the set of derived signals we want to keep as long as the widget exists. If the graphical object gets `destroy`ed, I have a callback that closes the signals in `preserved` and then empties the vector.

Specifically with regards to timers, I wonder: have you seen performance issues created by having a lot of them open at once? In stuff I'll be tackling soon, I plan to allow the user to change the framerate. Currently that seems to require creating a new `fps` object. If users open several windows at once and change the framerates routinely, then we could end up with dozens of timers firing uselessly every 30ms or so, and I worry that this might cause trouble. If that is a problem (and I have no idea whether it is), what about creating timers using a `Nullable{Timer}` (so you can replace the timer internally with one firing at a different rate) and giving them `stop/start` semantics?

Another advantage of that strategy is that by re-using the old timer object, I don't have to figure out how to untangle the web of derived signals from the first timer.
