### ISSUE TITLE
Running from function

### ISSUE THREAD

**Issue by cfitz25** [JuliaGizmos/GtkReactive.jl#108]
Hello, ive been trying to run this library from inside a function, this causes it to not react to mouse clicks from within code.
Is this meant to be occuring or have i done something wrong? 

    sigclick = map(d["gui"]["canvas"].mouse.buttonpress) do btn
        if(btn.button == 1)
            #println(btn.position)
            push!(e.last_points, (btn.position.x.val, btn.position.y.val))
            if(length(e.last_points) > max_points)
                splice!(e.last_points,1)
            end
            println(size(e.last_points)," ",e.last_points)
        end
    end

**Comment by timholy** [comment]
You need to hold on to `sigclick`, it's likely being garbage-collected. See the docs.
