### ISSUE TITLE
Gtk Grid?

### ISSUE THREAD

**Issue by tomerarnon** [JuliaGizmos/GtkReactive.jl#15]
Is there some way to arrange objects (boxes, canvases, buttons, etc.) using `Grid()` or something like it?
Attempting to place a `canvas` into a grid yields:

> LoadError: MethodError: no method matching unsafe_convert(::Type{Ptr{Gtk.GLib.GObject}}, ::GtkReactive.Canvas{GtkReactive.UserUnit})

**Comment by timholy** [comment]
Right now I bet you have to say `g[i,j] = widget(c)`. But I should make it so you can say `g[i,j] = c`.

**Comment by tomerarnon** [comment]
`g[i,j] = widget(c)` was indeed the solution.

It also required specifying `setproperty!(widget(c), :expand, true)` but otherwise behaves exactly as expected.
Thanks!

**Comment by timholy** [comment]
Convenience method added in #26.
