### ISSUE TITLE
SpinButton

### ISSUE THREAD

**Issue by yakir12** [JuliaGizmos/GtkReactive.jl#16]
So, I can imagine that any/all of the existing Gtk widgets will want to get wrapped up by a Reactive Signal. I for one would welcome a `SpinButton`. I could try to take a stab at doing exactly that... Or would you rather?

**Comment by timholy** [comment]
I'm busy making big changes to Interpolations, so I would welcome help!!

**Comment by yakir12** [comment]
I'll try!

**Comment by timholy** [comment]
Closed by #17
