### ISSUE TITLE
Signal connections

### ISSUE THREAD

**Issue by tomerarnon** [JuliaGizmos/GtkReactive.jl#19]
This isn't an issue with the package in any way, only with my understanding of it. I have a limited knowledge of Julia in general, and Gtk in particular, so delving into the source code hasn't done much to help me.
That said, I am migrating some of my code from GtkUtilties to GtkReactive at the moment, and I'd like to be able to accomplish all of the same things while taking advantage of GtkReactive's more "streamlined" approach to signal handling.

Here is a very simple program that adds the value of two sliders together and prints the result to the console. It uses the `map() do` syntax that I have noticed the examples make use of. I am not happy with it at the moment, for several reasons.
```
using GtkReactive, Gtk.ShortNames
slider1 = slider(1:10)
slider2 = slider(1:10)
cb = checkbox(false, label ="sum")
box = Box(:v)

push!(box, slider1)
push!(box, slider2)
push!(box, cb)

win = Window()
push!(win, box)

add = map(cb) do clicked
    if clicked
        s = slider1.signal.value + slider2.signal.value
        println(s)
    end
end

change_value = map(slider1) do val1
    if  cb.signal.value
        s = val1 + slider2.signal.value
        println(s)
    end
end
change_value = map(slider2) do val2
    if  cb.signal.value
        s = slider1.signal.value + val2
        println(s)
    end
end
showall(win)
```
The first reason, is that this code works at all, despite overwriting the variable `change_value`.  I have no idea why this should be working at all, and yet it is.
The second reason is that it is quite verbose. I would prefer to connect both `slider1` and `slider2` as signals to the same operation, preferably combining that together with `cb` into a single function that responds to all 3 signals. I am sure that this is possible I just don't know how to do it with these new objects and notations, and was hoping for some guidance. 
The third reason is that I would actually like to write the result to a `textbox` for any of the signals, but initiating a textbox with any one of those signals yields an error.

Anyway, clarity with signals in this example will be very helpful for me moving forward with the GUI I am working on.

Thanks in advance!

**Comment by tomerarnon** [comment]
Equally odd, this adaptation of the previous code, using `signal_connect` in the traditional Gtk sense, behaves very strangely. The displayed number is the sum of the _previous_ two values held by the sliders. That is, if one slider was just pushed to from `5` to `3`, and the first remains at `5` the displayed value will be `10` and the _next_ value to be displayed will be the expected `8`
```
slider1 = slider(1:10)
slider2 = slider(1:10)
cb = checkbox(true, label ="sum")
box = Box(:v)

push!(box, slider1)
push!(box, slider2)
push!(box, cb)

win = Window()
push!(win, box)

function plus(b, s1, s2)
    if b.signal.value
        println("$(s1.signal.value) + $(s2.signal.value) = $(s1.signal.value + s2.signal.value)")
    end
end


click = signal_connect(cb.widget, "clicked") do x
    plus(cb, slider1, slider2)
end
slid = signal_connect(slider1.widget, "value_changed") do x
    plus(cb, slider1, slider2)
end
slid2 = signal_connect(slider2.widget, "value_changed") do x
    plus(cb, slider1, slider2)
end

showall(win)
```

**Comment by timholy** [comment]
I think this is mostly a question about how to use Reactive.jl. First, note that `map` can take two signals. Second, I might use `filterwhen`. Since these are short functions, I'm using `->` rather than `do`. It can then be a 1-liner:
```julia
sig = map(println, filterwhen(signal(cb), 0, map((val1, val2)->val1+val2, signal(slider1), signal(slider2))))
```
The fact that one has to use `signal` in various places is a bit of a wart; I should probably change GtkReactive to make that unnecessary.

**Comment by tomerarnon** [comment]
I will familiarize myself with Reactive.jl, in that case.
Any idea why the second example propagates the signal before updating its value?

**Comment by timholy** [comment]
Reactive is asynchronous and the Gtk signal handler runs first.
