### ISSUE TITLE
Allow for mutliple GtkReactives in one map

### ISSUE THREAD

**Issue by yakir12** [JuliaGizmos/GtkReactive.jl#22]
In `Reactive` you can conveniently have multiple `Signal`s in one `map`. In `GtkReactive`, you need to wrap each `GtkReactive` with a `signal` function if you want more than one `GtkReactive` in one map.

**Comment by timholy** [comment]
Fixed by #26 (specifically b44def429544380b1b1a329ac42a48d51087a63a).
