### ISSUE TITLE
Rubberband zoom problems with 2012 macbook pro OS X El Capitan

### ISSUE THREAD

**Issue by tomerarnon** [JuliaGizmos/GtkReactive.jl#24]
I've been using this package successfully on a 2015 macbook running macOS Sierra, but have also recently been working on a 2012 macbook pro. 

I just tried running the `imageviewer.jl` example and  `init_zoom_rubberband(c, zr)` doesn't work. There is no error message, and the image appears in the window as expected and can still be zoomed using `init_zoom_scoll(c,zr)`.

This may not be a worthwhile issue to deal with, but I thought it would be worth mentioning.

**Comment by timholy** [comment]
> This may not be a worthwhile issue to deal with, but I thought it would be worth mentioning.

It might be worth it, but without more information (which I recognize might be difficult to obtain) I don't have a clue how to tackle it. The best guess is that this is a Gtk issue. You could insert various `println` statements to see whether the Gtk callbacks are running.

**Comment by tomerarnon** [comment]
I'll give it a shot.
Any suggestions of where to print before I dive in?

**Comment by timholy** [comment]
The Gtk callback handlers for the mouse are [here](https://github.com/JuliaGizmos/GtkReactive.jl/blob/d2e0f5e671c876e277d41d92f767c20006f58dc2/src/graphics_interaction.jl#L595-L625). If those are getting called, then the problem lies elsewhere.

You should probably write any debugging statements as something like
```julia
function mousedown_cb{U}(ptr::Ptr, eventp::Ptr, handler::MouseHandler{U})
    @schedule println("in mousedown_cb")
    evt = unsafe_load(eventp)
    push!(handler.buttonpress, MouseButton{U}(handler.widget, evt))
    Int32(false)
end
```
because technically I think you're not allowed to task-switch during a callback handler.

**Comment by tomerarnon** [comment]
Based on the print statements, all of the mouse callbacks are in order, it appears, including the left-mouse-button+drag.

However, adding similar print statements at various point in `init_zoom_rubberband` yields interesting results.

The `init` block prints before the `if, elseif` statements whenever the mouse is pressed but won't print anything that is inside either `if` condition. So `initiate(btn)` and `reset(btn)` are never true.

The `drag` block prints once at the beginning of the program, but not at any other point, and the `finish` block never prints at all.

**Comment by timholy** [comment]
I may have figured this out, by accidentally turning on the NumLock on my laptop. A possible solution is in #26, can I ask you to test it?

**Comment by tomerarnon** [comment]
I just updated GtkReactive and tested this on that macbook, and it is indeed fixed!

**Comment by timholy** [comment]
Great, thanks so much for reporting back!
