### ISSUE TITLE
Too lazy

### ISSUE THREAD

**Issue by yakir12** [JuliaGizmos/GtkReactive.jl#6]
Combining Reactive with Gtk is awesome. Thank you!!!

Not sure if this is an issue, but:
If I make a textbox from a Signal:
```Julia
t = textbox("abc")
w = Window("example")
push!(w, t)
showall(w)
```
and in the created textbox, I edit the "abc" text, say erase the 'c', then this happens:
```Julia
julia> getproperty(t.widget,:text, String)
"ab"
julia> t.signal.value
"abc"
```
The change does not propagate to the signal before the user presses `Enter`, or a `push!`command is issued. 
One way around this is if the nature of the coupling between the Signal and the widget could be specified by the user. In this specific example, changing the Gtk signal from `activate` to `changed` might propagate the change all the way to the Signal.

**Comment by timholy** [comment]
Just FYI `textarea` already updates with each character. I'd be fine if you added a keyword argument to change the signal for `textbox`.

**Comment by yakir12** [comment]
OK! Trying.

**Comment by timholy** [comment]
One point of concern would be the behavior of a textbox with a range `11:19`. Currently you can delete the second digit and type a new one. But if the signal fires after each character, and the signal enforces the range, I suspect you're going to get an error.

**Comment by yakir12** [comment]
True. Well, right now, writing '12' in the textbox-slider example in the docs moves the slider to 11 and leaves the '12' text unchanged (as opposed to say correcting it to '11'). Both scenarios are related, and I'm not sure what's the best way to deal with either. 
In a way, it's the programmer's responsibility to know about the dangers of manually assigning the coupling between the widget and the Signal (with a keyword) under certain circumstances (like when also assigning a range to the GtkReactive widget).

**Comment by timholy** [comment]
Hmm, that's a bug.

Sure, I can live with the fact that certain setting combinations won't work.

**Comment by yakir12** [comment]
That was exciting. Thank you for that!
I couldn't come up with tests cause it would have required some human to edit the text in the `textbox`. Hope that's ok.

**Comment by timholy** [comment]
Not quite sure what "That was exciting" means...did you intend to submit a PR? I haven't seen one, perhaps you need to click on a link?

**Comment by yakir12** [comment]
OOps, forgot to do that last step.
This is exciting, cause it's the first pull request I've ever done!

**Comment by yakir12** [comment]
Shouldn't we be able to close this now?
