### ISSUE TITLE
A first example: GUI controls - namespace problem

### ISSUE THREAD

**Issue by pauljurczak** [JuliaGizmos/GtkReactive.jl#79]
````
using Gtk.ShortNames, GtkReactive
sl = slider(1:11)
win = Window("Testing") |> (bx = Box(:v))
push!(bx, sl)
showall(win)
````
produces `UndefVarError: showall not defined`. This example works fine with `using Gtk` added.

**Comment by timholy** [comment]
It's already fixed in the docs source, but it looks like the hosted docs haven't been updating due to [this line](https://github.com/JuliaGizmos/GtkReactive.jl/blob/0798153e1410dbbeaf183989b767297464b7f338/docs/make.jl#L10).  Should be fixed once #81 merges and there's time for the docs to rebuild.
